In [1]:
import pandas as pd

wynagrodzenia = {
    "Styczeń": [5000, 6000, 7000, 8000],
    "Luty": [5100, 6200, 7300, 8400]
}

In [2]:
df = pd.DataFrame(wynagrodzenia)

In [3]:
print(df)

   Styczeń  Luty
0     5000  5100
1     6000  6200
2     7000  7300
3     8000  8400

In [11]:
df.loc[0:2]

   Styczeń  Luty
0     5000  5100
1     6000  6200
2     7000  7300

In [18]:
df = pd.DataFrame(wynagrodzenia, index=["Pracownik A", "Pracownik B", "Pracownik C", "Pracownik D"])
df

             Styczeń  Luty
Pracownik A     5000  5100
Pracownik B     6000  6200
Pracownik C     7000  7300
Pracownik D     8000  8400